# Generated by Django 3.1 on 2020-08-07 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(default=None, unique=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Copier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color_mono', models.IntegerField(default=0)),
                ('bit', models.IntegerField(default=0)),
                ('model_name', models.CharField(max_length=150, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copiers', to='copier.company')),
                ('driver_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copiers', to='copier.driverfile')),
            ],
        ),
    ]
